var key = {
    "W" : Wall,
    "." : Floor,
    "E" : BExit,
    "#" : NoBreakWall,
    "A" : AbazonWall,
    "T" : TermiWall,
    "t" : TermiExit
}

//spawns: N - W - E - S

var rooms = {
    "Seed" : { //currently unused because it explodes everything
        0 : "TTTTTTTTT",
        1 : "T.......T",
        2 : "T.......T",
        3 : "T.......T",
        4 : "T.......T",
        5 : "T.......T",
        6 : "T.......T",
        7 : "T.......T",
        8 : "TTTTtTTTT",
        "tags": [],
        "exits" : [[4,0],[0,4],[8,4],[4,8]],
    },
    "Standard" : {
        0 : "####E####",
        1 : "#.......#",
        2 : "#.......#",
        3 : "#.......#",
        4 : "E.......E",
        5 : "#.......#",
        6 : "#.......#",
        7 : "#.......#",
        8 : "####E####",
        "tags": ["randomgen","randomwall"],
        "exits" : [[4,0],[0,4],[8,4],[4,8]],
    },
    "Empty" : {
        0 : "####E####",
        1 : "#.......#",
        2 : "#.......#",
        3 : "#.......#",
        4 : "E.......E",
        5 : "#.......#",
        6 : "#.......#",
        7 : "#.......#",
        8 : "####E####",
        "tags": ["randomgen"],
        "exits" : [[4,0],[0,4],[8,4],[4,8]],
    },
    "Triangle" : {
        0 : "#E#######",
        1 : "#..WWWWW#",
        2 : "#....WWW#",
        3 : "#......W#",
        4 : "E.......E",
        5 : "#......W#",
        6 : "#....WWW#",
        7 : "#..WWWWW#",
        8 : "#E#######",
        "tags": ["randomgen"],
        "exits" : [[1,0],[0,4],[8,4],[1,8]],
    },
    "Narrow" : {
        0 : "AA##EW#AA",
        1 : "AA#...#AA",
        2 : "AA#...#AA",
        3 : "AA#...#AA",
        4 : "AAE...EAA",
        5 : "AA#...#AA",
        6 : "AA#...#AA",
        7 : "AA#...#AA",
        8 : "AA##E##AA",
        "tags": ["randomgen"],
        "exits" : [[4,0],[2,4],[6,4],[4,8]],
    }
}